### ISSUE TITLE
Investigate HashiCorp license changes 

### ISSUE THREAD

**Issue by savitharaghunathan** [konveyor/operator#261]
Investigate the impact of HashiCorp license changes

```[tasklist]
### Tasks
- [x] github.com/hashicorp/errwrap v1.1.0 -  MPL 2.0 [CNCF GB Exception](https://github.com/cncf/foundation/blob/main/license-exceptions/cncf-exceptions-2022-04-12.json)
- [x] github.com/hashicorp/go-multierror v1.1.1 -  MPL 2.0 [CNCF GB Exception](https://github.com/cncf/foundation/blob/main/license-exceptions/cncf-exceptions-2022-04-12.json)
- [x] github.com/hashicorp/go-version v1.6.0 - MPL 2.0 [CNCF GB Exception](https://github.com/cncf/foundation/blob/main/license-exceptions/cncf-exceptions-2023-06-27.json)
- [x] github.com/hashicorp/hcl v1.0.0 -  MPL 2.0 [CNCF GB Exception](https://github.com/cncf/foundation/blob/main/license-exceptions/cncf-exceptions-2022-04-12.json)
- [ ] Vagrant in dev env and setup docs
```

CNCF Tracking issue: https://github.com/cncf/foundation/issues/617

**Comment by savitharaghunathan** [comment]
CNCF published some guidelines here - https://github.com/cncf/foundation/blob/main/source-available-recommendations.md

**Comment by sseago** [comment]
Yeah, we've been wondering the same about Velero use of hashicorp code. The first thing to do is figure out which hashicorp packages will actually get a license change. At least one source I saw suggested that while their product-oriented repos would all change to the new license, most of their libraries will not.

**Comment by sseago** [comment]
Looks like, of the packages mentioned above, the only one with a license change is vagrant -- the others are libraries which, as of 16 Aug 2023, still list MPL in repo-root/LICENSE. It looks like all of the products that are moving to the new license were updated on 10 Aug.

**Comment by savitharaghunathan** [comment]
> Looks like, of the packages mentioned above, the only one with a license change is vagrant -- the others are libraries which, as of 16 Aug 2023, still list MPL in repo-root/LICENSE. It looks like all of the products that are moving to the new license were updated on 10 Aug.

Thanks @sseago :)

**Comment by djzager** [comment]
Closing as I think our work here is done. Reopen otherwise please.
